from __future__ import annotations

from dataclasses import dataclass
from math import acos, pi
from typing import Sequence


@dataclass(frozen=True)
class RecoveryPhaseBlocks:
    """Explicit first-order ALEC phase blocks from Remark S4.11.

    The paper describes the shorthand recovery as four separate phase blocks.
    Keeping them grouped in a small dataclass makes the construction readable:

    - `eta1` through `eta4` are the four blocks from the remark.
    - `delta` is the auxiliary angle defined by Eq. (S59).
    - `m` and `n` are the free integers that parameterize the family.

    This object is intentionally phase-list only. It does not know anything
    about matrices, noisy evolutions, or fitting procedures.
    """

    eta1: tuple[float, ...]
    eta2: tuple[float, ...]
    eta3: tuple[float, ...]
    eta4: tuple[float, ...]
    delta: float
    m: int
    n: int

    @property
    def blocks(self) -> tuple[tuple[float, ...], ...]:
        """Return the four recovery blocks in paper order."""

        return (self.eta1, self.eta2, self.eta3, self.eta4)


def concatenate_qsp_phase_lists(
    left_phases: Sequence[float],
    right_phases: Sequence[float],
) -> tuple[float, ...]:
    """Return the phase list for the product `QSP(left) @ QSP(right)`.

    For QSP, two adjacent phase lists cannot simply be concatenated term-by-term.
    The last phase of the left list and the first phase of the right list sit on
    the same `Z` rotation once the two sequences are multiplied together, so they
    must be merged into a single angle.

    Concretely, if

    - `left = (a0, ..., ak)`
    - `right = (b0, ..., br)`

    then the product sequence is

    - `(a0, ..., a{k-1}, ak + b0, b1, ..., br)`.
    """

    if not left_phases or not right_phases:
        raise ValueError("both phase lists must contain at least one angle")

    return tuple(
        float(value)
        for value in (
            *left_phases[:-1],
            float(left_phases[-1]) + float(right_phases[0]),
            *right_phases[1:],
        )
    )


def apply_conjugation_to_phase_list(
    phases: Sequence[float],
    m: int,
    n: int,
    eta: float,
) -> tuple[float, ...]:
    """Apply one conjugation-chain update from Definition S1.8 / Eq. (S21).

    This is the basic symbolic step used in the degree-wise construction. The
    function takes an existing phase list and wraps it by the extra front/back
    phases prescribed by the paper.

    The parameters `m` and `n` are the integer degrees of freedom that appear in
    the theorem statement. In the current degree-wise construction we usually use
    `m = 0`, but the function keeps the full general form because that is the
    actual algebraic rule.
    """

    if not phases:
        raise ValueError("phases must contain at least one angle")

    return tuple(
        float(value)
        for value in (
            -(eta + pi * (2 * m + n + 0.5)),
            pi * (n + 0.5) + float(phases[0]),
            *(float(phase) for phase in phases[1:]),
            eta,
        )
    )


def _normalize_half_angle(angle: float) -> float:
    """Normalize a half-angle into the interval `(-pi, 0]`.

    The degree-wise formulas determine angles only up to shifts by integer
    multiples of `pi`. Normalizing them keeps the numerical representation stable
    and makes successive recovery blocks easier to inspect by eye.

    The interval here matches the convention used in the original monolithic
    prototype.
    """

    while angle > 0.0:
        angle -= pi
    while angle <= -pi:
        angle += pi
    return float(angle)


def _conjugation_chain_phase_list(
    etas: Sequence[float],
    *,
    n: int,
) -> tuple[float, ...]:
    """Build the phase list generated by repeatedly applying the conjugation rule.

    The chain always starts from the trivial one-phase sequence `(0.0,)`, which
    represents the identity QSP sequence in the phase-list algebra used here.
    Each `eta` extends the current list by one more conjugation step.

    This helper is private because it is an internal assembly primitive for the
    recovery constructions rather than a user-facing API.
    """

    phases = (0.0,)
    for eta in etas:
        phases = apply_conjugation_to_phase_list(phases, 0, n, float(eta))
    return phases


def recovery_delta(phi: float, n: int) -> float:
    """Return the auxiliary angle `delta` from Eq. (S59).

    Eq. (S59) defines

    - `delta = 1/2 arccos(phi / (n pi))`.

    The formula only makes sense when `n != 0` and when the arccos argument lies
    in `[-1, 1]`, so both conditions are validated explicitly.
    """

    if n == 0:
        raise ValueError("n must be non-zero")

    argument = phi / (n * pi)
    if argument < -1.0 or argument > 1.0:
        raise ValueError(
            f"phi / (n pi) must lie in [-1, 1], received {argument} for phi={phi}, n={n}"
        )

    return 0.5 * acos(argument)


def build_recovery_phase_blocks_k1(
    phi: float,
    depth: int,
    *,
    m: int = 0,
    n: int = 1,
) -> RecoveryPhaseBlocks:
    """Assemble the explicit first-order shorthand blocks from Remark S4.11.

    This function is for the special case where the original QSP sequence uses a
    single repeated phase `phi` and has QSP degree `depth`.

    For that setting, Remark S4.11 gives four blocks:

    - two blocks with `+delta`
    - two blocks with `-delta`
    - and the center phases shifted by integer multiples of `2 pi` / `4 pi`

    The repeated `-phi` and `phi + 2 pi m` segments encode the left and right
    "tails" that mirror the original degree.
    """

    if depth < 1:
        raise ValueError("depth must be positive")

    delta = recovery_delta(phi, n)

    # Each block has the same internal shape. Only the first, middle, and last
    # entries differ between eta1..eta4. These repeated tails are factored out so
    # the block definitions mirror the paper more directly.
    left_repeats = [-phi] * (depth - 1)
    right_repeats = [phi + 2.0 * pi * m] * (depth - 1)

    eta1 = (
        -phi - pi - delta,
        *left_repeats,
        pi / 2.0,
        *right_repeats,
        phi + pi / 2.0 + delta,
    )
    eta2 = (
        -phi - 4.0 * n * pi - delta,
        *left_repeats,
        4.0 * n * pi - pi / 2.0,
        *right_repeats,
        phi + pi / 2.0 + delta,
    )
    eta3 = (
        -phi - pi + delta,
        *left_repeats,
        pi / 2.0,
        *right_repeats,
        phi + pi / 2.0 - delta,
    )
    eta4 = (
        -phi - 4.0 * n * pi + delta,
        *left_repeats,
        4.0 * n * pi - pi / 2.0,
        *right_repeats,
        phi + pi / 2.0 - delta,
    )

    return RecoveryPhaseBlocks(
        eta1=tuple(float(value) for value in eta1),
        eta2=tuple(float(value) for value in eta2),
        eta3=tuple(float(value) for value in eta3),
        eta4=tuple(float(value) for value in eta4),
        delta=float(delta),
        m=m,
        n=n,
    )


def recovery_phase_list_k1_shorthand(
    phi: float,
    depth: int,
    *,
    m: int = 0,
    n: int = 1,
) -> tuple[float, ...]:
    """Collapse the four Remark S4.11 blocks into one recovery phase list.

    The shorthand recovery is defined as the product of the four blocks in order.
    We therefore start from the trivial one-phase identity list `(0.0,)` and
    repeatedly compose in each block using the QSP concatenation rule.
    """

    blocks = build_recovery_phase_blocks_k1(phi, depth, m=m, n=n)
    recovery_phase_list = (0.0,)
    for phase_block in blocks.blocks:
        recovery_phase_list = concatenate_qsp_phase_lists(recovery_phase_list, phase_block)
    return recovery_phase_list


__all__ = [
    "RecoveryPhaseBlocks",
    "apply_conjugation_to_phase_list",
    "build_recovery_phase_blocks_k1",
    "concatenate_qsp_phase_lists",
    "recovery_delta",
    "recovery_phase_list_k1_shorthand",
    "_conjugation_chain_phase_list",
    "_normalize_half_angle",
]
